version: "3.7"
services:
  meshi-nari:
    build: .
    environment:
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
  mysql:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
volumes:
  mysql-data:
    driver: local
